services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: devops-platform-app

    ports:
      - "8080:8080"

    environment:
      DATABASE_URL: postgres://app:app_password@postgres:5432/devops?sslmode=disable

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped


  postgres:
    image: postgres:17-alpine

    container_name: devops-platform-postgres

    ports:
    - "5432:5432"

    environment:
      POSTGRES_DB: devops
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_password

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d devops"]
      interval: 5s
      timeout: 5s
      retries: 5

    restart: unless-stopped


volumes:
  postgres_data: